// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	Say(ctx context.Context, opts ...grpc.CallOption) (Chat_SayClient, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Say(ctx context.Context, opts ...grpc.CallOption) (Chat_SayClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], "/Chat/Say", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatSayClient{stream}
	return x, nil
}

type Chat_SayClient interface {
	Send(*ServerMessage) error
	Recv() (*ClientMessage, error)
	grpc.ClientStream
}

type chatSayClient struct {
	grpc.ClientStream
}

func (x *chatSayClient) Send(m *ServerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatSayClient) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
// All implementations should embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	Say(Chat_SayServer) error
}

// UnimplementedChatServer should be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) Say(Chat_SayServer) error {
	return status.Errorf(codes.Unimplemented, "method Say not implemented")
}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_Say_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Say(&chatSayServer{stream})
}

type Chat_SayServer interface {
	Send(*ClientMessage) error
	Recv() (*ServerMessage, error)
	grpc.ServerStream
}

type chatSayServer struct {
	grpc.ServerStream
}

func (x *chatSayServer) Send(m *ClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatSayServer) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Say",
			Handler:       _Chat_Say_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}
